services:
    web:
        container_name: web
        build:
            context: .
            dockerfile: ./apps/web/Dockerfile
        restart: always
        ports:
            - 3000:3000
        networks:
            - app_network
    api:
        container_name: api
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
        restart: always
        ports:
            - 3001:3001
        networks:
            - app_network
            - db_network
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: doctors-calendar
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - db_network

volumes:
    db-data:

networks:
    db_network:
    app_network:
