packages:
    - "apps/*"
    - "packages/*"

catalog:
    react: ^18.2.0
    react-dom: ^18.2.0
    "@types/react": ^18.2.61
    "@types/react-dom": ^18.2.19
    eslint: ^9.17.0
    prettier: ^3.2.5
    typescript: 5.5.4
